kind: pipeline
type: docker
name: main-ci

trigger:
  event: push
  branch: v2

steps:
  - name: npm install
    image: node:20
    commands:
      - node -v
      - npm -v
      - npm ci

  - name: Check prettier
    image: node:20
    commands:
      - npm run check-format

  - name: Check that it builds
    image: node:20
    commands:
      - npm run build

  - name: Vercel deploy to prod
    image: node:20
    environment:
      VERCEL_ORG_ID: team_qEUZmPwX3J0FFDAk23fSvIlq
      VERCEL_PROJECT_ID: prj_XD11Fr78qNrfVoaAa46D1iAvIQIT
      VERCEL_TOKEN:
        from_secret: vercel-token
    commands:
      - npm install --global vercel@34.1.7
      - vercel pull --yes --environment=production --scope i-exec --token $VERCEL_TOKEN
      - VITE_APP_COMMIT=${DRONE_COMMIT} vercel build --prod --scope i-exec --token $VERCEL_TOKEN
      - vercel deploy --prod --prebuilt --scope i-exec --token $VERCEL_TOKEN

---
kind: pipeline
type: docker
name: preview-ci

trigger:
  event: push
  branch:
    exclude:
      - production
      - staging
      - v2

steps:
  - name: npm install
    image: node:20
    commands:
      - node -v
      - npm -v
      - npm ci

  - name: Check prettier
    image: node:20
    commands:
      - npm run check-format

  - name: Check that it builds
    image: node:20
    commands:
      - npm run build

  - name: Vercel deploy to preview
    image: node:20
    environment:
      VERCEL_ORG_ID: team_qEUZmPwX3J0FFDAk23fSvIlq
      VERCEL_PROJECT_ID: prj_XD11Fr78qNrfVoaAa46D1iAvIQIT
      VERCEL_TOKEN:
        from_secret: vercel-token
    commands:
      - npm install --global vercel@34.1.7
      - vercel pull --yes --environment=preview --scope i-exec --token $VERCEL_TOKEN
      - VITE_APP_COMMIT=${DRONE_COMMIT} vercel build --scope i-exec --token $VERCEL_TOKEN
      - vercel deploy --prebuilt --scope i-exec --token $VERCEL_TOKEN
