name: preview-ci

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_TOOLS_DOC_PROJECT_ID }}

on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - 'README.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: |
          node -v
          npm -v
          npm ci --no-fund

      - name: Check Prettier
        run: npm run check-format

      - name: Set Vercel Token
        id: set-vercel-token
        run: |
          if [ "${{ github.actor }}" = "ErwanDecoster" ]; then
            echo "vercel_token=${{ secrets.VERCEL_TOKEN_ERWAN }}" >> $GITHUB_OUTPUT
          else
            echo "vercel_token=${{ secrets.VERCEL_TOKEN }}" >> $GITHUB_OUTPUT
          fi

      - name: Vercel deploy to preview
        run: |
          npm install --global vercel@latest
          vercel pull --yes --scope i-exec --token=${{ steps.set-vercel-token.outputs.vercel_token }}
          vercel build --scope i-exec --token=${{ steps.set-vercel-token.outputs.vercel_token }}
          vercel deploy --prebuilt --scope i-exec --token=${{ steps.set-vercel-token.outputs.vercel_token }}
