name: preview-ci

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_TOOLS_DOC_PROJECT_ID }}

on:
  push:
    branches:
      - v2-greg

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: |
          node -v
          npm -v
          npm ci --no-fund

      - name: Check Prettier
        run: npm run check-format

      - name: Vercel deploy to preview-greg
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          chmod +x ./deployDomain.sh
          ./deployDomain.sh
